dist: trusty
sudo: required
language: 
  - cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - cmake

script: 
  - export CXX=/usr/bin/g++-6
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - g++ -v
  - cd test && cmake .. && make && ctest -VV
  - cmp cpp_git.out python_git.out
  - cat cpp_git.out
  - cat python_git.out
