version: "{build}"

os:
  - Visual Studio 2017
  - Visual Studio 2015

platform:
  - x64

configuration:
  - Debug
  - Release

environment:
  matrix:
  - PYTHON: "C:\\Python36-x64"

before_build:
  - set PATH=%PYTHON%;%PATH%
  - cmake -H. -Btest -A%PLATFORM%

build:
  project: test/git_info_test.sln
  parallel: true

test_script:
  - cd test
  - ctest -C %CONFIGURATION% -VV
  - rename python_git.out python_git_clean.out
  - cd ..
  - type nul > dirty_file
  - git add -A
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - git commit -m "test'"
  - msbuild test/git_info_test.sln /t:Clean;Rebuild /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cd test
  - ctest -C %CONFIGURATION% -VV
  - python -c "import sys; from filecmp import cmp; sys.exit(1) if cmp('python_git_clean.out', 'python_git.out', shallow=False) else sys.exit(0)"
